version: 0.0
os: linux
files:
  - source: /index.html
    destination: /home/ec2-user/deploy
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: ec2-user
    - location: scripts/start_server
      timeout: 300
      runas: ec2-user
